### PR TITLE
check if err is nil on metrics server run

### LINKED ISSUE #118: Nil pointer dereference in metrics server error logging when error is nil
## Summary
The bosh-dns service panics with a segmentation fault due to a nil pointer dereference when logging metrics server errors on Ubuntu Noble.

## Environment
- **OS**: Ubuntu Noble (24.04)
- **Configuration**: systemd-resolve enabled

## Error Details
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb047a5]

goroutine 49 [running]: main.mainExitCode.func2() /var/vcap/data/compile/bosh-dns/src/bosh-dns/dns/main.go:254 +0x45 created by main.mainExitCode in goroutine 1 /var/vcap/data/compile/bosh-dns/src/bosh-dns/dns/main.go:252 +0x246a

## Root Cause
In [`/var/vcap/data/compile/bosh-dns/src/bosh-dns/dns/main.go` around line 254](https://github.com/cloudfoundry/bosh-dns-release/blob/master/src/bosh-dns/dns/main.go#L254), the code logs an error without checking if it's nil:

```go
err := metricsServerWrapper.Run(shutdown)
logger.Error(logTag, "could not start metric server: %s", err.Error())
```

When metricsServerWrapper.Run(shutdown) succeeds and returns nil, calling err.Error() causes a nil pointer dereference.

## Proposed Fix
Add a nil check before logging the error: 
```go
err := metricsServerWrapper.Run(shutdown)
if err != nil {
    logger.Error(logTag, "could not start metric server: %s", err.Error())
}
```

### PR DESCRIPTION
**Pull request by dudejas**
Fixes https://github.com/cloudfoundry/bosh-dns-release/issues/118

### CODE REVIEW

**Review by neddp — APPROVED** [review]

File: src/bosh-dns/dns/main.go [hunk 1]
```diff
@@ -251,7 +251,9 @@ func mainExitCode() int {
 	if metricsServerWrapper != nil {
 		go func() {
 			err := metricsServerWrapper.Run(shutdown)
-			logger.Error(logTag, "could not start metric server: %s", err.Error())
+			if err != nil {
+				logger.Error(logTag, "could not start metric server: %s", err.Error())
```
Comment (dudejas) [inline src/bosh-dns/dns/main.go]:
```suggestion
				logger.Error(logTag, "could not start metrics server: %s", err.Error())
```

**Review by a-hassanin — APPROVED** [review]
I don't know how this did not cause issues before, but the change makes sense.

**Review by a-hassanin — CHANGES_REQUESTED** [review]
Please enhance the tests.

**Review by aramprice — DISMISSED** [review]

**Review by rkoster — DISMISSED** [review]

**Comment by dudejas** [comment]
Thanks for approving, @aramprice and @rkoster, added some tests now as @a-hassanin suggested.

File: README.md [hunk 2]
```diff
@@ -18,3 +18,23 @@ This repository is a `GOPATH`. The [`.envrc`](.envrc) file provides a setup that
...
+sudo ifconfig lo0 alias 127.0.0.3 up
+sudo ifconfig lo0 alias 127.0.0.253 up
+sudo ifconfig lo0 alias 127.0.0.254 up
+sudo sysctl -w kern.ipc.somaxconn=1024  # default is 128
+```
+
+Then run the tests:
+
+```bash
+ginkgo -v --procs=1 src/bosh-dns/dns/
```
Comment (aramprice) [inline README.md:45]: Maybe this should be 

```shell
./scripts/test-unit
```

Or alternately to use `go run` so that the expected version of Ginkgo is executed (and the user doesn't need to have it already installed). Something like:

```shell
cd src/bosh-dns/dns/
 go run github.com/onsi/ginkgo/v2/ginkgo run -v ./...
```

Q: is `--procs=1` required in all cases?

**Review by aramprice — DISMISSED** [review]
Thank you for adding tests!

I added a comment about the README update though I'm fine merging as is.

File: src/bosh-dns/dns/main_test.go [hunk 3]
```diff
@@ -1875,6 +1875,94 @@ var _ = Describe("main", func() {
...
+				apiPort, err := testhelpers.GetFreePort()
+				Expect(err).NotTo(HaveOccurred())
+
+				metricsPort, err := testhelpers.GetFreePort()
+				Expect(err).NotTo(HaveOccurred())
+
+				// Create a conflict by binding to the metrics port first
+				conflictListener, err := net.Listen("tcp", fmt.Sprintf("127.0.0.1:%d", metricsPort))
+				Expect(err).NotTo(HaveOccurred())
+				defer conflictListener.Close()
```
Comment (aramprice) [inline src/bosh-dns/dns/main_test.go]:
```suggestion
				defer conflictListener.Close() //nolint:errcheck
```

File: README.md (hunk 2 above)
Comment (a-hassanin) [reply README.md:45]: You are right ./scripts/test-unit does contain more tests. I added it.

I also left ginkgo as a way to run specific test suits. I did not see a difference when using --procs=1, but may be it is safer to use it any how in case there are some unknown dependencies.

I will merge as is.

**Review by a-hassanin — APPROVED** [review]
Thanks @dudejas !
